# Generated by Django 5.2.1 on 2025-05-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livraria", "0004_livro_autores"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="autor",
            options={"verbose_name_plural": "Autores"},
        ),
        migrations.AlterField(
            model_name="autor",
            name="email",
            field=models.EmailField(default="autor@exemplo.com", max_length=254),
            preserve_default=False,
        ),
    ]
